version: "3.8"

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: on-failure
