"""Add fixtures table

Revision ID: ededa5a5fc22
Revises: 
Create Date: 2023-11-05 01:20:32.105210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ededa5a5fc22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('full_time_home_goals', sa.Integer(), nullable=False),
    sa.Column('full_time_away_goals', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('result', postgresql.ENUM('HOME', 'DRAW', 'AWAY', name='fixtureresult'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
